tp2_Grupo2/src/main/resources/templates/index.html

Se terminó con el diseñó de la página index.html

Información de patitas felices aside, article, footer

---

tp2_Grupo2/src/main/resources/templates/contactos.html

se agrega pagina html para contactos

---

tp2_Grupo2/src/main/resources/templates/index.html

Se agrega viewport y se corrige header

Agregar viewport y corrección de header

---

tp2_Grupo2/src/main/resources/templates/paseos.html

Agrego pagina paseo

---

tp2_Grupo2/src/main/resources/templates/contactos.html

creacion de pagina de contacta para agregar el encabezado de la pagina inicio

agregado de encabezado a la pagina de contactos

---

tp2_Grupo2/src/main/resources/templates/consejossalud.html

Se realiza una modificación en la página consejosalud

Modificación en la página consejosalud

---

tp2_Grupo2/src/main/resources/templates/paseos.html

modificacion de paseos

---

tp2_Grupo2/src/main/resources/templates/paseos.html

modificacion 2 paseos

---

tp2_Grupo2/src/main/resources/templates/sucursales.html

Sucursales

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

contenido a index, se agrega navegación a productos.html.

Se comienza con el TP3, se sube archivo estilo.css, se modifica y agrega

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/index.html

Se agrega id y clases a la página index.html y se le agrega estilo

Se agrega id, clases y estilo para la página index.html

---

tp2_Grupo2/src/main/resources/templates/productos.html

por error se subieron los cambios a la rama master directamente y quedaron guardados en lugar de trabajar en otra rama

se agregan mas estilos a contactos

---

tp2_Grupo2/src/main/resources/templates/paseos.html

se modifica encabezado pagina paseos

se modifica encabezado pagina paseos

---

tp2_Grupo2/bin/src/main/resources/static/css/estilo.css
tp2_Grupo2/bin/src/main/resources/templates/sucursales.html

Subo actualizacion de la fuente de la pagina sucursales

Se modifica fuente (usuario:alumno es SaraDMercado)

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html

Se agrega clase e id a la página consejos de salud, y se agrega comentarios importantes por favor leer estimados porfesores.

Comentarios importantes, leer por favor estimados profesores.

---

tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/layouts/footer.html
tp2_Grupo2/src/main/resources/templates/layouts/header.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Agrego carpeta layouts y los archivos footer y header y referencias

Agrego carpeta Layouts y los archivos footer y header

---

tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Agrego referencias del header y footer a cada pagina html

Agrego referencias del header y footer a cada pagina html

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/IndexController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaPaseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Paseo.java

Agrego paquetes Controller,Listas y Model

Agrego paquetes Controller,Listas y Model

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/IndexController.java
tp2_Grupo2/src/main/resources/templates/index.html

Codifico clase index controller en la capa controladora

Codifico clase index controller en la capa controladora

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaPaseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Paseo.java
tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Agrego página nuevo_paseo para dar la alta de un paseador, le agrego estilo a la página.
Codifico clase PaseoController, ListaPaseo y Paseo.

Agrego página nuevo_paseo y clase PaseoController

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejosSaludController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Consejo.java
tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html

Se crea la clase Consejo(paquete model) con los atributos, constructores y setters y getters.
Se cre la clase ListaConsejo (paquete listas) con el arrylist que contiene objetos tipo Consejo, constructor por defecto y los getters y setters. En esta clase se agregan objetos al arraylist usando el constructor por defecto.
Se crea la clase ConsejosSaludController (paquete controller) que contiene los metodos y peticiones necesarias para el alta, modificacion o eliminacion de un objeto tipo Consejo.
Se agrega el archivo nuevo_consejo.html para para agregar/modificar un consejo.
Se modifica consejossalud.html para que muestre los consejos del arraylist y las opciones para el alta, modificacion y eliminacion de un consejo.
Se modifica estilos.css para los estilos necesarios de las paginas …

Modificaciones

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ContactosController.java

Se crea ContactosController para acceder a la pagina contactos.html

Modificaicon

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Sucursal.java
tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Subo Sucursales

---

tp2_Grupo2/src/main/resources/templates/sucursales.html

Se  agrega estilo a las tabla de sucursales.

Se agrega estilo y corrección

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html

Se cambian estilos de la pagina consejos de salud

Modificacion

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html
tp2_Grupo2/src/main/resources/templates/nuevo_producto.html
tp2_Grupo2/src/main/resources/templates/productos.html

Se cabia los estilos de los encabazados y links de las paginas contactos.html, consejossalud.html, nuevo_consejo.html, nuevo_producto.html, Se agrega el calculo del precio con descuento a la informacion del producto, se modifica el paquete controller para que se haga la busqueda con en nro de codigo del producto

Cambio de estilos en paginas:

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/index.html

Se corrige estilo en index para que sea similar a las demás páginas.

Se corrige estilo en index.html

---

tp2_Grupo2/pom.xml
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/nuevo_producto.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Subo archivo Pom y link de bootstrap

Agrego dependencias al archivo pom.xml

---

tp2_Grupo2/src/main/resources/static/css/estilo.css
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/layouts/header.html
tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/nuevo_producto.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Se agrega encabezado y pie de página a todas las páginas html.

Se agrega encabezado y pie de página a todas las páginas html

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejosSaludController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Consejo.java

pagina consejossalud
Se adaptaron las clases del paqute model con @Component

agregado de validaciones y captacion de errores en paquetes para la

---

tp2_Grupo2/src/main/resources/templates/consejossalud.html

Se incorporó el uso de bootstrap para la pagina consejossalud

Modificacion de pagina consejossalud con boostrap

---

tp2_Grupo2/src/main/resources/templates/contactos.html

Aplico estilos en contactos.html

Se aplica bootstrap a página contactos

---

tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html

Se modifica la pagina nuevo_consejo con estilos boostrap y se agregan controles para mostrar al usuario mensajes para el ingreso correcto de datos

Incorporacion de bootstrap y mensajes de validacion de errores en formulario nuevo_consejo

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaPaseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Paseo.java
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/paseos.html

Agrego estilo bootstrap a las páginas paseos, e inyecciones a su clase.

Agrego estilo bootstrap a las páginas paseos, e inyecciones a su clase.

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejosSaludController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Consejo.java
tp2_Grupo2/src/main/resources/messages.properties
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html

Se realizan las correciones para la validacion de ingreso de datos durante la modificación de un consejo, se agregaron los margenes correspondientes a la pagina consejossalud

Correcciones tp5

---

tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html

Se modifica el formulario nuevo consejo para evitar que se modifique este campo durante la edicion

Se agrega control para evitar cambio de idConsejo en modificacion

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/resources/templates/consejossalud.html
tp2_Grupo2/src/main/resources/templates/contactos.html
tp2_Grupo2/src/main/resources/templates/index.html
tp2_Grupo2/src/main/resources/templates/nuevo_consejo.html
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/nuevo_producto.html
tp2_Grupo2/src/main/resources/templates/paseos.html
tp2_Grupo2/src/main/resources/templates/productos.html

Arreglo titulos de las páginas, iconos de la páginas.
Arreglo error tp5 con paseadores.

Subo modificacion de dieseño y solucion de paseadores

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaPaseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/model/Paseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IPaseoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/PaseoServiceImp.java

Subo interfaz IPaseoService, su codificación y documentación.
Subo clase PaseoServicioImp, su codificación y documentación.

Subo Interfaz y Clase de Interfaz

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejosSaludController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java

Interfaz Consejo y su documentacion. Subo Clase ConsejoServiceImp y su documentacion

Interfaz documentacion consejo

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejosSaludController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Consejo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Paseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Producto.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaPaseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaProducto.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IPaseoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProductoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/PaseoServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java

Se cambia el nombre del paquete model por entity usando refactor -> rename

modificacion nombre paquete model

---

tp2_Grupo2/pom.xml

Agregado al paquete pom las dependencias Spring boot starter data jpa y MySql conector java

Se agregan dependencias

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java

Se agregó notaciones pertenecientes al paquete jakarta.persistence (@entity, @table, @id, @column)
, un atributo de tipo Long con nombre id y notación @id.
Se agregó el nombre de la columna (@column) para cada atributo de las clases
, un atributo de tipo boolean denominado estado, que indica si el objeto está activo o no. Si se quiere eliminar un objeto se utilizará el estado = false, cuando se crea un nuevo objeto el estado siempre tiene valor true
Se agregó documentación

Modificacion clase Sucursal

---

tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html

Modificacion parte de formulario

---

tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html

Se modifica el formulario de alta de la sucursal
Esta tarea fue compartida con SaraDMercado

Mofificacion formulario de alta sucursal

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java

Se creo el servicio SucursalServiceMysqlImp para realizar las consultas en la base de datos
Se actualizó el servicio SucursalServiceImp
Se agrego documentacion

Creacion del servicio SucursalServiceMysqlImp

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
tp2_Grupo2/src/main/resources/templates/sucursales.html

Se completo los metodos deI servicio SucursalServiceMysqlImp
Se modificó SucursalController para implentar correctamente SucursalServiceMysqlImp
Se cambio el servicio SucursalServiceImp para que pueda ser usado correctamente si se requiere
Se modifico la pagina sucursales para que se puede modificar/eliminar una sucursal de la base de datos mediente su id
Se agregó documentacion de codigo

Req 5 interfaz sucursal co

---

tp2_Grupo2/src/main/resources/templates/nueva_sucursal.html

Se modifica el formaulario de alta para vincular el alta con la clase provincia

Modificacion en formulario de alta

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Provincia.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/repository/IProvinciaRepository.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProvinciaService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ProvinciaServiceMysqlImp.java

Se agrega la clase provincia, el servicio provincia y la interfaz necesaria para el mapeo Sucursal-Provincia 
Se agrega documentacion correspondiente

Agregado clase Provincia e Interfaz Provincia

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProvinciaService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
tp2_Grupo2/src/main/resources/templates/sucursales.html

Se modifica la clase sucursal para realizar el mapeo con la clase Provincia
Se modifica el controlador de sucursal para agregar el servicio relacionado a la clase provicia
Se agrega el metodo para buscar entre fechas las sucursales
Se modifica la pagina sucursales para agregar la opcion de buscar entre fechas las sucursales
Se agreda documentacion al codigo
Se corrige el nombre de ContactosController por ContactoController

Modificacion en el controlador, servicio e interfaz de Sucursal

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Provincia.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java

Se modifica la interfaz, el servicio, la implementación y el controlador para listar las sucursales entre dos fechas
Se agrega el método de busqueda correspondiente
Se agrega documentación

Modificaciones en interfaz sucursal

---

tp2_Grupo2/src/main/resources/templates/sucursales.html

Se modifica la pagina sucursales para realizar la busqueda entre dos fechas

modificacion en pagina sucursales

---

tp2_Grupo2/src/main/resources/templates/sucursales.html

Se corrige posicion de boton LISTADO COMPLETO

se modifica posicion de boton

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/GestionController.java
tp2_Grupo2/src/main/resources/templates/gestion.html
tp2_Grupo2/src/main/resources/templates/layouts/header.html

Agrego clase GestionController
Agrego a la barra de navegacion el enlace Gestion de Datos

agrego gestion de datos a la barra de navegacion

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Paseo.java
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/paseos.html

Elimino idservicio en clase Paseo, para que se maneje solo con la Id de la Base de Datos.

Elimino idservicio en Paseo

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Empleado.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/entity/Paseo.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/repository/IEmpleadoRepository.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IEmpleadoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/EmpleadoServiceMysqlImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/PaseoServiceImp.java
tp2_Grupo2/src/main/resources/templates/nuevo_paseo.html
tp2_Grupo2/src/main/resources/templates/paseos.html

Realizo mapeo para la relación Empleado-Servicio

Agrego mapeo Empleado-Servicio

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/PaseoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/repository/IPaseoRepository.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IPaseoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/PaseoServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/PaseoServiceMysqlImp.java
tp2_Grupo2/src/main/resources/templates/paseos.html

Se crea filtro por día en Servicios

Se crea filtro por día en Servicios

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ConsejoSaludController.java

Se cambia el nombre de ConsejosController por ConsejoControlle y se agrega @Qualifier("ConsejoServiceMysql")

correciones

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ICategoriaService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IEmpleadoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IPaseoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProductoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProvinciaService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
tp2_Grupo2/src/main/resources/application.properties
tp2_Grupo2/src/main/resources/templates/productos.html
tp2_Grupo2/src/main/resources/templates/sucursales.html

Se agrega la configuracion de application.properties
Se quita el @Service de las interfaces de ar.edu.unju.fi.service
Se quitan los botones de agregado de las paginas productos, sucursales, consejos

Correcciones varias

---

tp2_Grupo2/src/main/resources/templates/consejossalud.html

Se quita el boton de agregrar consejo a la pagina

Modificacion pagina consejossalud

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/IProductoService.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
tp2_Grupo2/src/main/resources/templates/productos.html

Se corrige la busqueda por producto

Correccion busqueda producto

---

tp2_Grupo2/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
tp2_Grupo2/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java

se quita codigo comentado innecesario.
Con este commit se da por finalizada las correcciones del tp 7

quitado de codigo inecesario
